---

- name: create static content location
  file: path="{{ static_content_location }}" state=directory mode=0755
  become: true

- name: Create default index.html
  template: src="index.html.j2" dest="{{ static_content_location }}/index.html" mode="u=rw,g=rw,o=r"
  become: true

- name: Create conf location
  file: path="{{ nginx_servers_conf_location }}" state=directory mode=0755
  become: true

- name: Upload nginx.conf
  copy: src=nginx.conf dest="{{ nginx_conf_location }}" mode="u=rw,g=r,o=r"
  become: true
  notify: Restart nginx

- name: Upload default.conf
  copy: src=nginx.default.conf dest="{{ nginx_servers_conf_location }}/{{ default_conf_file }}" mode="u=rw,g=r,o=r"
  become: true
  notify: Restart nginx

- name: List all servers conf files
  shell: ls -1 {{ nginx_servers_conf_location }}
  register: contents
  changed_when: false

- name: Set list of managed servers conf files
  set_fact: managed_conf_files="{{ [ default_conf_file ] + reverse_proxyfied_domains|map(attribute='domain')|map('regex_replace', '(.*)', '\\1.conf') | list }}"

- name: Delete all unmanaged servers conf files
  file: path={{ nginx_servers_conf_location }}/{{ item }} state=absent
  with_items: "{{contents.stdout_lines}}"
  when: item not in managed_conf_files
  notify: Restart nginx
  become: true

- name: Upload reverse proxy server confs
  template: src="reverse_proxyfied_domain.conf.j2" dest="{{ nginx_servers_conf_location }}/{{ item.domain }}.conf" mode="u=rw,g=rw,o=r"
  with_items: "{{ reverse_proxyfied_domains }}"
  notify: Restart nginx
  become: true

- name: flush to evaluate nginx restart variable
  meta: flush_handlers

- name: Create nginx container
  become: true
  docker_container:
    name: nginx
    image: nginx
    state: started
    restart: "{{restart_nginx|default(false)}}"
    ports:
      - "80:80"
    volumes:
      - "{{ static_content_location }}:{{ docker_static_content_location }}:ro"
      - "{{ nginx_conf_location }}:/etc/nginx/nginx.conf:ro"
      - "{{ nginx_servers_conf_location }}:/etc/nginx/conf.d:ro"