---

- name: create static content location
  file: path="{{ static_content_location }}" state=directory mode=0755
  become: true

- name: Create default index.html
  template: src="index.html.j2" dest="{{ static_content_location }}/index.html" mode="u=rw,g=rw,o=r"
  become: true

- name: Create nginx container
  become: true
  docker_container:
    name: nginx
    image: nginx
    state: started
    ports:
      - "80:80"
    volumes:
      - "{{ static_content_location }}:/usr/share/nginx/html:ro"