---

- hosts: server
  vars_prompt:
      - name: "ssh_priv_key_pass"
        prompt: 'Passphrase of private ssh key ?'
  roles:
    - { role: disk_mounting, dm_ciphering_ssh_priv_key_pass: "{{ ssh_priv_key_pass }}" }
    - { role: reverse_proxy }
    - { role: password_manager }
