---

- hosts: server
  vars_prompt:
      - name: "dm_ciphering_ssh_priv_key_pass"
        prompt: 'Passphrase of private ssh key ?'
  roles:
    - role: etc_hosts
    - role: base_setup
    - role: disk_mounting
