mail_domain: moi.ovh

mail_users: []

#mail_users:
#  - {
#    username: bfiorentino,
#    password_hash: "{SHA512-CRYPT}$7$P8ooOOplljj$KF7788kjj$hkjh7jghjg.R4.bE1S50",
#    aliases: ["bastien.fiorentino", "bastien", "bfi", "b"],
#    aliases_regex: ["^b_.+", "^bfi_.+", "^bfiorentino_.+"]
#  }

mail_containers_conf_root_location: "/etc/containers"
mail_containers_data_root_location: "/data/containers"
mail_conf_location: "{{ mail_containers_conf_root_location }}/mail"
mail_data_location: "{{ mail_containers_data_root_location }}/mail"
mail_mailboxes_location: "{{ mail_data_location }}/mailboxes"
mail_sieveboxes_location: "{{ mail_data_location }}/sieveboxes"

mail_certificate_location: "{{ mail_containers_conf_root_location }}/reverse_proxy/certs/live/mail.{{ mail_domain }}/fullchain.pem"
mail_certificate_key_location: "{{ mail_containers_conf_root_location }}/reverse_proxy/certs/live/mail.{{ mail_domain }}/privkey.pem"

mail_dkim_private_key_location: "{{ mail_conf_location }}/certs/dkim/mail.private"