---

mattermost_user_app_config:
  ServiceSettings:
    SiteURL: 'https://slack.moi.ovh'
    EnableOAuthServiceProvider: true
    EnableCustomEmoji: true
    EnableGifPicker: true
    EnableEmailInvitations: true
  TeamSettings:
    SiteName: Slack
  EmailSettings:
    SendEmailNotifications: true
    RequireEmailVerification: true
    EnableSMTPAuth: true
    SMTPUsername: 'user@gmail.com'
    SMTPPassword: 'PASSWORD'
    SMTPServer: 'smtp.gmail.com'
    SMTPPort: '587'
    ConnectionSecurity: 'STARTTLS'
  SupportSettings:
    SupportEmail: fiorentino.bastien@gmail.com
