---

dependencies:
  - role: base/docker
  - role: base/ansible_dependencies
    dependency_roles:
      - src: "git+https://github.com/BastienF/ansible-mattermost-in-docker"
        version: master
  - role: reverse_proxy
