---

- include_role:
    name: .galaxy/ansible-mattermost-in-docker
  vars:
    mattermost_root_location: "/data/containers/mattermost"
    mattermost_docker_networks:
      - name: "{{ bfiven_docker_network }}"
    mattermost_user_app_config:
      ServiceSettings:
        SiteURL: 'https://slack.moi.ovh'
        EnableOAuthServiceProvider: true
        EnableCustomEmoji: true
        EnableGifPicker: true
        EnableEmailInvitations: true
      TeamSettings:
        SiteName: Slack
      EmailSettings:
        SendEmailNotifications: true
        RequireEmailVerification: true
        EnableSMTPAuth: true
        SMTPUsername: "{{ mattermost_EmailSettings_SMTPUsername }}"
        SMTPPassword: "{{ mattermost_EmailSettings_SMTPPassword }}"
        SMTPServer: 'smtp.gmail.com'
        SMTPPort: '587'
        ConnectionSecurity: 'STARTTLS'
        SendPushNotifications: true
        PushNotificationServer: 'http://{{ mattermost_push_proxy_container_name }}:8066'
      SupportSettings:
        SupportEmail: fiorentino.bastien@gmail.com
      PasswordSettings: {}
      PrivacySettings: {}
      LocalizationSettings: {}
      DataRetentionSettings: {}
