---

reverse_proxy_endpoints:
  transmission:
    host: "transmission.{{ domain }}"
    dest: "http://{{ transmission_container_name }}:9091"
    host_gen_cert: true
    basicAuth: "{{ download_manager_basic_auths }}"
  jackett:
    host: "jackett.{{ domain }}"
    dest: "http://{{ jackett_container_name }}:9117"
    host_gen_cert: true
    basicAuth: "{{ download_manager_basic_auths }}"
  sonarr:
    host: "download.{{ domain }}"
    dest: "http://{{ sonarr_container_name }}:8989"
    host_gen_cert: true
    basicAuth: "{{ download_manager_basic_auths }}"
  jellyfin:
    host: "media.{{ domain }}"
    dest: "http://{{ jellyfin_container_name }}:8096"
    host_gen_cert: true
  password_manager:
    host: "passwords.{{ domain }}"
    dest: "http://{{ password_manager_container }}"
    host_gen_cert: true
  file_sync:
    host: "files.{{ domain }}"
    dest: "http://{{ syncthing_container_name }}:8384"
    host_gen_cert: true
    basicAuth: "{{ syncthing_basic_auths }}"
  mattermost:
    host: "slack.{{ domain }}"
    dest: "http://{{ mattermost_app_container_name }}:8000"
    host_gen_cert: true
  mastodon:
    host: "suivez.{{ domain }}"
    dest: "http://{{ mastodon_web_container_name }}:3000"
    host_gen_cert: true
  mastodon_streaming:
    host: "streaming.suivez.{{ domain }}"
    dest: "http://{{ mastodon_streaming_container_name }}:4000"
    host_gen_cert: true

reverse_proxy_root_location: "/data/containers/{{ reverse_proxy_container_name }}"
