---

reverse_proxy_containers_conf_root_location: "/etc/containers"
reverse_proxy_conf_location: "{{ reverse_proxy_containers_conf_root_location }}/reverse_proxy"

reverse_proxy_letsencrypt_challenge_location: "{{ reverse_proxy_conf_location }}/www/letsencrypt_challenge"
reverse_proxy_cetificates_location: "{{ reverse_proxy_conf_location }}/certs"
reverse_proxy_live_certs_location: "{{ reverse_proxy_cetificates_location }}/live"
reverse_proxy_trusted_ca_location: "{{ reverse_proxy_cetificates_location }}/certificate_authorities"
reverse_proxy_use_staging_cert: false

reverse_proxy_nginx_configuration_location: "{{ reverse_proxy_conf_location }}/nginx"
reverse_proxy_nginx_conf_location: "{{ reverse_proxy_nginx_configuration_location }}/nginx.conf"
reverse_proxy_nginx_servers_conf_location: "{{ reverse_proxy_nginx_configuration_location }}/conf.d"

reverse_proxy_container_name: reverse_proxy

reverse_proxy_exposed_http_port: 80
reverse_proxy_exposed_https_port: 443

reverse_proxy_domains : []
##Exemple
#reverse_proxy_domains :
#  - {
#      domain: toto.ovh,
#      redirect_server: perdu.com,
#      https: {
#        port: 443,
#        certificate_mail: moi@moi.ovh
#      },
#      http: {
#        port: 80
#      }
#    }
#  - {
#      domain: tata.ovh,
#      redirect_server: perdu.com,
#      http: {
#        port: 80
#      }
#    }

reverse_proxy_local_name_resolution: []
##Exemple
#reverse_proxy_local_name_resolution: >
#  {
#    "bbright": "192.168.0.11",
#    "bfiven": "192.168.0.10"
#  }