# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# IP addresses of the nodes
@subnet = "192.168.10"
init_script = "init-ansible-debian.sh"
init_script_dest = "/tmp/#{init_script}"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "bfivendev" do |config|
    config.vm.host_name = "bfivendev"
    config.vm.network "private_network", ip: "#{@subnet}.10"
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", 4]
      vb.memory = 2048
    end
  end
  config.vm.provision "shell", :privileged => true, inline: "apt-get install -y python"
  config.vm.provision "shell", :privileged => true, inline: "source <(curl -s https://raw.githubusercontent.com/BastienF/CustomCloud/master/init-ansible-debian.sh)"
  config.vm.provision "shell", :privileged => true, inline: "sed -i 's/Port 22/Port 6022/g' /etc/ssh/sshd_config; systemctl restart sshd"
end