---

all:
  children:
    server:
      hosts:
        bfivendev:
          is_prod: false
          domain: "moi.ovh.local"
    local:
      hosts:
        localhost:
          ansible_connection: local
          syncthing_user: "bastien"
