---

all:
  children:
    server:
      hosts:
        bfiven:
          is_prod: true
          domain: "moi.ovh"
          syncthing_user: "ansible"
          vpn_port: 11194
    local:
      hosts:
        localhost:
          ansible_connection: local
          syncthing_user: "bastien"
