---

- name: Install role dependencies
  local_action: command ansible-galaxy install --roles-path ./roles/.galaxy {{ dependency.src }},{{ dependency.version }} --force
  with_items: "{{ dependency_roles }}"
  register: result
  changed_when: false
  loop_control:
    loop_var: dependency
