---

- include: handle_nginx_container.yml
  vars:
    docker_restart: false
    docker_state: absent

- name: Erase container data
  file: path="{{ webserver_conf_location }}" state=absent
  become: true